apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argus-rules
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.revision }}
    path: observability/rules
  {{- include "argus.syncPolicy" (list "SkipDryRunOnMissingResource=true") | nindent 2 }}
